modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="worldclock"
version="1.2.1 Beta"
displayName="World Clock"
logoFile="worldclock.png"
credits="Sources written by Shadow_Hawk. Ported to Forge by LiskoSlayer63."
authors="LiskoSlayer63, Shadow_Hawk"
description='''
Provides a clock face and hands for the Minecraft world time and the time your computer displays -- perfect for use with fullscreen.

'''

[[dependencies.worldclock]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="CLIENT"

[[dependencies.worldclock]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="CLIENT"